name: CI

on: [push]

jobs:
  build:
  
    runs-one: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello World!
    - name: Run a multi-line script
      run:
        echo Add other action to build,
        echo test, and deploy your project.
