#------------------------------------------------------
# Github Actions part-1-basics
#
# Copyright (c) Vitalii Pekshev

name: assignment-devops

on: 
  push:
    branches:
      - master

jobs:
  build:
  
    runs-one: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello World!
    - name: Run a multi-line script
      run:
        echo Add other action to build,
        echo test, and deploy your project.
